# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About"
  weight = 20

[[main]]
  parent = "About"
  name = "What is ESCALATOR?"
  url = "#about"
  weight = 10

[[main]]
  parent = "About"
  name = "Our community"
  url = "people/"
  weight = 20

[[main]]
  parent = "About"
  name = "Working groups"
  url = "groups/"
  weight = 30

[[main]]
  parent = "About"
  name = "Code of Conduct"
  url = "conduct/"
  weight = 40

[[main]]
  parent = "About"
  name = "Contact"
  url = "contact/"
  weight = 40

[[main]]
  name = "DH-IGNITE"
  url = "dh-ignite/"
  weight = 30

  [[main]]
    parent = "DH-IGNITE"
    name = "Information"
    url = "dh-ignite/"
    weight = 10


  [[main]]
    parent = "DH-IGNITE"
    name = "Past: 18 - 19 Oct 2022 (KwaZulu Natal)"
    url = "past_dh_ignites/kzn/"
    weight = 60

  [[main]]
    parent = "DH-IGNITE"
    name = "Past: 8 - 10 March 2023 (Western Cape)"
    url = "past_dh_ignites/wc/"
    weight = 50


  [[main]]
    parent = "DH-IGNITE"
    name = "Past: 23 - 25 August 2023 (Central & Western Regions)"
    url = "past_dh_ignites/cwr/"
    weight = 40



  [[main]]
    parent = "DH-IGNITE"
    name = "Past: 27 Nov - 1 Dec 2023 (Eastern Cape)"
    url = "https://dh2023.digitalhumanities.org.za/"
    weight = 30


  [[main]]
    parent = "DH-IGNITE"
    name = "Past: 15 - 17 April 2024 (Northern Region)"
    url = "past_dh_ignites/nr/"
    weight = 20


[[main]]
  name = "Champions Initiative"
  url = "champions/overview/"
  weight = 40

  [[main]]
    parent = "Champions Initiative"
    name = "Overview"
    url = "champions/overview/"
    weight = 10

  [[main]]
    parent = "Champions Initiative"
    name = "Explorer"
    url = "champions/explorer/"
    weight = 20

  [[main]]
    parent = "Champions Initiative"
    name = "Embarker"
    url = "champions/embarker/"
    weight = 30

  [[main]]
    parent = "Champions Initiative"
    name = "Enhancer"
    url = "champions/enhancer/"
    weight = 40

  [[main]]
    parent = "Champions Initiative"
    name = "Enabler"
    url = "champions/enabler/"
    weight = 50

  [[main]]
    parent = "Champions Initiative"
    name = "Educator"
    url = "champions/educator/"
    weight = 60

  [[main]]
    parent = "Champions Initiative"
    name = "Empower "
    url = "champions/empower/"
    weight = 70

  [[main]]
    parent = "Champions Initiative"
    name = "Engager (SWiP) "
    url = "champions/engager/"
    weight = 80

  [[main]]
    parent = "Champions Initiative"
    name = "Exchanger "
    url = "champions/exchanger/"
    weight = 90

[[main]]
  name = "Stakeholder Map"
  weight = 50

  [[main]]
    parent = "Stakeholder Map"
    name = "Interactive visualisations"
    url = "stakeholder-map/"
    weight = 10

  [[main]]
    parent = "Stakeholder Map"
    name = "Project info"
    url = "stakeholder-map-info/"
    weight = 20

  [[main]]
    parent = "Stakeholder Map"
    name = "Add your data"
    url = "stakeholder-map-data/"
    weight = 30


  [[main]]
    parent = "Stakeholder Map"
    name = "Workflow development"
    url = "/post/2022/04/intro-stakeholdermap-workflow/"
    weight = 40

[[main]]
  name = "Events"
  weight = 60
  url = "events/"


[[main]]
  name = "Resources"
  weight = 70

  [[main]]
    parent = "Resources"
    name = "SA training initiatives & communities"
    url = "initiatives/"
    weight = 10

   [[main]]
    parent = "Resources"
    name = "Global training resources"
    url = "global-training-resources/"
    weight = 20

  [[main]]
    parent = "Resources"
    name = "Useful tools in DH & CSS"
    url = "useful-tools/"
    weight = 30

  [[main]]
    parent = "Resources"
    name = "YouTube playlists"
    url = "https://www.youtube.com/channel/UCcLjjFCG2SNzZhxUJZyLcLg/playlists"
    weight = 40

  [[main]]
    parent = "Resources"
    name = "Zenodo Open Documents"
    url = "https://zenodo.org/communities/escalator/?page=1&size=20"
    weight = 50 

  [[main]]
    parent = "Resources"
    name = "Information leaflets & publications"
    url = "publication"
    weight = 60 



[[main]]
  name = "Blog"
  url = "post/"
  weight = 80

[[main]]
  name = "Connect"
  url = "connect/"
  weight = 90




# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
